[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Meteor Shower Replace Planet Cards
[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'before'
pattern = '''
card:start_materialize({G.C.WHITE, G.C.WHITE}, nil, 1.5*G.SETTINGS.GAMESPEED)
'''
payload = '''
if booster_obj.kind == 'Celestial' then
    for _, joker in ipairs(SMODS.find_card('j_monarchy_meteor_shower')) do
        _card = joker.config.center:create_card(joker)
        if _card then
            card:remove()
            card = _card
            break
        end
    end
end
'''

# One in the Chamber: remove all hands when played
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'at'
pattern = '''
ease_hands_played(-1)
'''
payload = '''
if next(SMODS.find_card('j_monarchy_one_chamber')) then
    ease_hands_played(-G.GAME.current_round.hands_left)
    G.E_MANAGER:add_event(Event({
        func = function()
            play_sound('monarchy_gunshot')
            return true
        end
    }))
else
    ease_hands_played(-1)
end
'''
